apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.0.5-172.16.0.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nginxl2
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
